<?php

function theme_register_resource_post_type() {
  register_post_type('resource', [
    'label' => __('Resource', 'takt'),
    'labels' => [
      'name'                  => __('Resources', 'takt'),
      'singular_name'         => __('Resource', 'takt'),
      'add_new'               => __('Add New', 'takt'),
      'add_new_item'          => __('Add New Resource', 'takt'),
      'edit_item'             => __('Edit Resource', 'takt'),
      'new_item'              => __('New Resource', 'takt'),
      'view_item'             => __('View Resource', 'takt'),
      'view_items'            => __('View Resources', 'takt'),
      'search_items'          => __('Search Resources', 'takt'),
      'not_found'             => __('No Resources found', 'takt'),
      'not_found_in_trash'    => __('No Resources found in Trash', 'takt'),
      'parent_item_colon'     => __('Parent Resource:', 'takt'),
      'all_items'             => __('All Resources', 'takt'),
      'archives'              => __('Resource Archives', 'takt'),
      'attributes'            => __('Resource Attributes', 'takt'),
      'insert_into_item'      => __('Insert into Resource', 'takt'),
      'uploaded_to_this_item' => __('Uploaded to this Resource', 'takt'),
      'featured_image'        => __('Featured Image', 'takt'),
      'set_featured_image'    => __('Set featured image', 'takt'),
      'remove_featured_image' => __('Remove featured image', 'takt'),
      'use_featured_image'    => __('Use as featured image', 'takt'),
      'menu_name'             => __('Resources', 'takt'),
      'filter_items_list'     => __('Filter Resources list', 'takt'),
      'items_list_navigation' => __('Resources list navigation', 'takt'),
      'items_list'            => __('Resources list', 'takt'),
      'name_admin_bar'        => __('Resource', 'takt'),
    ],
    'description'         => __('Resources and materials.', 'takt'),
    'public'              => true,
    'exclude_from_search' => false,
    'publicly_queryable'  => true,
    'show_ui'             => true,
    'show_in_nav_menus'   => false,
    'show_in_menu'        => true,
    'show_in_admin_bar'   => true,
    'menu_position'       => 6,
    'menu_icon'           => 'dashicons-portfolio',
    'capability_type'     => 'post',
    'hierarchical'        => false,
    'supports'            => ['title', 'editor', 'excerpt', 'thumbnail', 'revisions', 'custom-fields'],
    'taxonomies'          => [],
    'has_archive'         => true,
    'rewrite'             => [
      'slug'       => 'resources',
      'with_front' => false,
      'pages'      => true,
      'feeds'      => true,
    ],
    'query_var'       => true,
    'can_export'      => true,
    'delete_with_user' => null,
    'show_in_rest'    => true,
  ]);
}
add_action('init', 'theme_register_resource_post_type');
